CREATE TABLE Comments (
  commentID VARCHAR(255) PRIMARY KEY,
  userID VARCHAR(255) REFERENCES Users(userID),
  postID VARCHAR(255) REFERENCES Posts(postID),
  content VARCHAR(500) NOT NULL ,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

