CREATE TABLE Posts (
    postID VARCHAR(255) PRIMARY KEY,
    userID VARCHAR(255) REFERENCES Users(userID),
    caption VARCHAR(400) NOT NULL,
    postImage VARCHAR(1000) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Posts;
