CREATE TABLE Replies (
  replyID VARCHAR(255) PRIMARY KEY,
  userID VARCHAR(255) REFERENCES Users(userID),
  commentID VARCHAR(255) REFERENCES Comments(commentID),
  text VARCHAR(500) NOT NULL ,
  createdAt VARCHAR(300)
);