###
POST http://localhost:3700/users/register/
Content-Type: application/json

{
    "fullName": "Isaac Kiptoo",
    "username": "_@isookip",
    "profileImage": "https://media.istockphoto.com/id/1437816897/photo/business-woman-manager-or-human-resources-portrait-for-career-success-company-we-are-hiring.webp?b=1&s=612x612&w=0&k=20&c=hEPh7-WEAqHTHdQtPrfEN9-yYCiPGKvD32VZ5lcL6SU=",
    "email": "isaackilimok2@gmail.com",
    "password": "12345678@Ik"
}


### login 
POST http://localhost:3700/users/login/
Content-Type: application/json

{
   "email": "isaackilimok2@gmail.com",
   "password": "12345678@ik" 
}

### fetching all users
GET http://localhost:3700/users/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5NzVlMDgxOS05Nzc0LTQ2ZTAtODliZS0xNWM5MDU2ZGI4OTciLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsInVzZXJuYW1lIjoiaXNhYWNraXAiLCJlbWFpbCI6ImlzYWFja2lsaW1vQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjpmYWxzZSwiaXNTZW5kIjpmYWxzZSwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9tZWRpYS5pc3RvY2twaG90by5jb20vaWQvMTQzNzgxNjg5Ny9waG90by9idXNpbmVzcy13b21hbi1tYW5hZ2VyLW9yLWh1bWFuLXJlc291cmNlcy1wb3J0cmFpdC1mb3ItY2FyZWVyLXN1Y2Nlc3MtY29tcGFueS13ZS1hcmUtaGlyaW5nLndlYnA_Yj0xJnM9NjEyeDYxMiZ3PTAmaz0yMCZjPWhFUGg3LVdFQXFIVEhkUXRQcmZFTjkteVlDaVBHS3ZEMzJWWjVsY0w2U1U9IiwiaWF0IjoxNzAyMzkwOTU0LCJleHAiOjE3MDI1NjM3NTR9.t5M0xosvx1C2vMA-lz6nxe5VLEAEvHi3u4aNF-Z23l8


###update user
PUT http://localhost:3700/users/update/975e0819-9774-46e0-89be-15c9056db897/
Content-Type: application/json

{
    "fullName": "isaac kil",
    "username": "_@isaackil",
    "profileImage": "https://media.istockphoto.com/id/1483487030/photo/portrait-of-a-female-avatar-made-for-web3-and-the-metaverse.webp?b=1&s=612x612&w=0&k=20&c=ZJwbU6nXo3V7zq7Bvj-KX9xgAQhousVvI9o2UmB7eDc="
}

### fetching single user
GET http://localhost:3700/users/singleUser/975e0819-9774-46e0-89be-15c9056db897/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5NzVlMDgxOS05Nzc0LTQ2ZTAtODliZS0xNWM5MDU2ZGI4OTciLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsInVzZXJuYW1lIjoiaXNhYWNraXAiLCJlbWFpbCI6ImlzYWFja2lsaW1vQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjpmYWxzZSwiaXNTZW5kIjpmYWxzZSwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9tZWRpYS5pc3RvY2twaG90by5jb20vaWQvMTQzNzgxNjg5Ny9waG90by9idXNpbmVzcy13b21hbi1tYW5hZ2VyLW9yLWh1bWFuLXJlc291cmNlcy1wb3J0cmFpdC1mb3ItY2FyZWVyLXN1Y2Nlc3MtY29tcGFueS13ZS1hcmUtaGlyaW5nLndlYnA_Yj0xJnM9NjEyeDYxMiZ3PTAmaz0yMCZjPWhFUGg3LVdFQXFIVEhkUXRQcmZFTjkteVlDaVBHS3ZEMzJWWjVsY0w2U1U9IiwiaWF0IjoxNzAyMzkwOTU0LCJleHAiOjE3MDI1NjM3NTR9.t5M0xosvx1C2vMA-lz6nxe5VLEAEvHi3u4aNF-Z23l8


### fetching user
GET http://localhost:3700/users/userDetails/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5NzVlMDgxOS05Nzc0LTQ2ZTAtODliZS0xNWM5MDU2ZGI4OTciLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsInVzZXJuYW1lIjoiaXNhYWNraXAiLCJlbWFpbCI6ImlzYWFja2lsaW1vQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjpmYWxzZSwiaXNTZW5kIjpmYWxzZSwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9tZWRpYS5pc3RvY2twaG90by5jb20vaWQvMTQzNzgxNjg5Ny9waG90by9idXNpbmVzcy13b21hbi1tYW5hZ2VyLW9yLWh1bWFuLXJlc291cmNlcy1wb3J0cmFpdC1mb3ItY2FyZWVyLXN1Y2Nlc3MtY29tcGFueS13ZS1hcmUtaGlyaW5nLndlYnA_Yj0xJnM9NjEyeDYxMiZ3PTAmaz0yMCZjPWhFUGg3LVdFQXFIVEhkUXRQcmZFTjkteVlDaVBHS3ZEMzJWWjVsY0w2U1U9IiwiaWF0IjoxNzAyMzkwOTU0LCJleHAiOjE3MDI1NjM3NTR9.t5M0xosvx1C2vMA-lz6nxe5VLEAEvHi3u4aNF-Z23l8

### reset password
POST http://localhost:3700/users/initiate-password-reset/
Content-Type: application/json

{
   "email": "isaackilimok2@gmail.com" 
}

### reset password
POST http://localhost:3700/users/reset-password/
Content-Type: application/json

{
   "email": "isaackilimok2@gmail.com",
   "resetToken":"beeb3fc3-eb4e-47cf-abc4-b5adaae64339",
   "newPassword":"12345678@ik" 
}


### checking user details
GET http://localhost:3700/users/checkUserDetails/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJiNjc3ZDk2NC01ZTIxLTQyMDItOGJjNC1iNzc5ZDcyMzExZTAiLCJmdWxsTmFtZSI6Impvc2h1YSBvbW9uZGkiLCJlbWFpbCI6Impvc2h1YW9tb25kaTMzMzRAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwicmVzZXRQYXNzd29yZFRva2VuIjpudWxsLCJyZXNldFBhc3N3b3JkRXhwaXJlcyI6bnVsbCwid2VsY29tZWQiOnRydWUsImlhdCI6MTcwMTE4NzE4OSwiZXhwIjoxNzAxMzU5OTg5fQ.0hRlKsXGtEKP8_MP--ROem0zMLUBlePZA2-VFI2mmBY


#### deleting user
DELETE http://localhost:3700/users/delete/975e0819-9774-46e0-89be-15c9056db897/

###### creating new product
POST http://localhost:3700/posts/create
Content-Type: application/json

{
    "name": "new Tv Stand",
    "shortDescription": "This is a good Tv stand for modern house",
    "price": 2200,
    "image": "https://media.istockphoto.com/id/937510970/photo/smart-tv-mockup-with-black-glossy-screen-on-console-in-living-room.jpg?s=2048x2048&w=is&k=20&c=0_fvqr0Hrqd3NR9C5tsDF2ys6rQQBJEcYI_o6fyvlg0="
}

### fetching all posts

GET http://localhost:3700/posts/all


### fetching one post
GET http://localhost:3700/posts/single/82B7DAD8-DA99-40FB-B143-1D2AD2437D64/


###### Updating post
PUT  http://localhost:3700/posts/update/82B7DAD8-DA99-40FB-B143-1D2AD2437D64/
Content-Type: application/json

{
    "name": "Black Tv Stand",
    "shortDescription": "They are remainin two in stock",
    "price": 2800,
    "image": "https://media.istockphoto.com/id/1430080532/photo/bedroom-without-sheets.webp?b=1&s=612x612&w=0&k=20&c=7_c725vsPgGRxQJLD13VAt5zOk6TvFT4KWZba4RYBfg="
  }

### search post by types
GET http://localhost:3700/posts/search?type=GA


# Deleting a post
###
DELETE http://localhost:3700/posts/delete/492776AB-44CC-4468-B1B2-207C35E2B87C/


