###
POST http://localhost:3700/users/register/
Content-Type: application/json

{
    "fullName": "Daniel Kitheka",
    "username": "_@Dankitheka254",
    "email": "gamemy1774@gmail.com",
    "password": "12345678@Dk"
}



### login 
POST http://localhost:3700/users/login/
Content-Type: application/json

{
   "email": "isaackilimok2@gmail.com",
   "password": "12345678@Ik" 
}

### fetching all users
GET http://localhost:3700/users/all/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5OWUxOGYzYS1mN2Q5LTRiYjctODBlMi1iOWYxN2JkMjA4MWIiLCJmdWxsTmFtZSI6ImlzYWFjIGtpbGltbyIsInVzZXJuYW1lIjoiQGlzYWFjMTIzNCIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNTZW5kIjpmYWxzZSwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9tZWRpYS5pc3RvY2twaG90by5jb20vaWQvMTMwMDg0NTYyMC92ZWN0b3IvdXNlci1pY29uLWZsYXQtaXNvbGF0ZWQtb24td2hpdGUtYmFja2dyb3VuZC11c2VyLXN5bWJvbC12ZWN0b3ItaWxsdXN0cmF0aW9uLmpwZz9zPTYxMng2MTImdz0wJms9MjAmYz15QmV5YmEwaFVraDE0X2pndjFPS3FJSDBDQ1NXVV80Y2tSa0FveTJwNzNvPSIsImlhdCI6MTcwMjkyNjA4NSwiZXhwIjoxNzAzMDk4ODg1fQ.9t02Me_WQ6jZeKwjljxW0oIp0YtDjHvooEaJcLG7W68

#### getting users
GET http://localhost:3700/users/all/99e18f3a-f7d9-4bb7-80e2-b9f17bd2081b
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5OWUxOGYzYS1mN2Q5LTRiYjctODBlMi1iOWYxN2JkMjA4MWIiLCJmdWxsTmFtZSI6ImlzYWFjIGtpbGltbyIsInVzZXJuYW1lIjoiQGlzYWFjMTIzNCIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNTZW5kIjpmYWxzZSwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9tZWRpYS5pc3RvY2twaG90by5jb20vaWQvMTMwMDg0NTYyMC92ZWN0b3IvdXNlci1pY29uLWZsYXQtaXNvbGF0ZWQtb24td2hpdGUtYmFja2dyb3VuZC11c2VyLXN5bWJvbC12ZWN0b3ItaWxsdXN0cmF0aW9uLmpwZz9zPTYxMng2MTImdz0wJms9MjAmYz15QmV5YmEwaFVraDE0X2pndjFPS3FJSDBDQ1NXVV80Y2tSa0FveTJwNzNvPSIsImlhdCI6MTcwMjkyNjA4NSwiZXhwIjoxNzAzMDk4ODg1fQ.9t02Me_WQ6jZeKwjljxW0oIp0YtDjHvooEaJcLG7W68

###update user
PUT http://localhost:3700/users/update/13994250-847e-4545-9232-af9cd787b196/
Content-Type: application/json

{
    "fullName": "Daniel Kitheka2",
    "username": "_@Dankitheka254",
    "profileImage": "https://media.istockphoto.com/id/1483487030/photo/portrait-of-a-female-avatar-made-for-web3-and-the-metaverse.webp?b=1&s=612x612&w=0&k=20&c=ZJwbU6nXo3V7zq7Bvj-KX9xgAQhousVvI9o2UmB7eDc="
}

### fetching single user
GET http://localhost:3700/users/singleUser/13994250-847e-4545-9232-af9cd787b196/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3NzY3Nzc3NS0xODNhLTQ4YzktODAxMC1jNzc3MGEzZTk4NGUiLCJmdWxsTmFtZSI6IkVyaWNrIEt5YWxvIiwidXNlcm5hbWUiOiJfQGVyaWNrMTIzIiwiZW1haWwiOiJlcmlja2t5YWxvQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjp0cnVlLCJpc1NlbmQiOmZhbHNlLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL21lZGlhLmlzdG9ja3Bob3RvLmNvbS9pZC8xMzAwODQ1NjIwL3ZlY3Rvci91c2VyLWljb24tZmxhdC1pc29sYXRlZC1vbi13aGl0ZS1iYWNrZ3JvdW5kLXVzZXItc3ltYm9sLXZlY3Rvci1pbGx1c3RyYXRpb24uanBnP3M9NjEyeDYxMiZ3PTAmaz0yMCZjPXlCZXliYTBoVWtoMTRfamd2MU9LcUlIMENDU1dVXzRja1JrQW95MnA3M289IiwiaWF0IjoxNzAyNjMxMjI3LCJleHAiOjE3MDI4MDQwMjd9.vPEqXjXa9thiIXSdPFq6WTRaAtv5-hkSxqhxwuUDMMY


### fetching user
GET http://localhost:3700/users/userDetails/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3NzY3Nzc3NS0xODNhLTQ4YzktODAxMC1jNzc3MGEzZTk4NGUiLCJmdWxsTmFtZSI6IkVyaWNrIEt5YWxvIiwidXNlcm5hbWUiOiJfQGVyaWNrMTIzIiwiZW1haWwiOiJlcmlja2t5YWxvQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjp0cnVlLCJpc1NlbmQiOmZhbHNlLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL21lZGlhLmlzdG9ja3Bob3RvLmNvbS9pZC8xMzAwODQ1NjIwL3ZlY3Rvci91c2VyLWljb24tZmxhdC1pc29sYXRlZC1vbi13aGl0ZS1iYWNrZ3JvdW5kLXVzZXItc3ltYm9sLXZlY3Rvci1pbGx1c3RyYXRpb24uanBnP3M9NjEyeDYxMiZ3PTAmaz0yMCZjPXlCZXliYTBoVWtoMTRfamd2MU9LcUlIMENDU1dVXzRja1JrQW95MnA3M289IiwiaWF0IjoxNzAyNjMxMjI3LCJleHAiOjE3MDI4MDQwMjd9.vPEqXjXa9thiIXSdPFq6WTRaAtv5-hkSxqhxwuUDMMY


### reset password
POST http://localhost:3700/users/initiate-password-reset/
Content-Type: application/json

{
   "email": "gamemy177@gmail.com" 
}


### reset password
POST http://localhost:3700/users/reset-password/
Content-Type: application/json

{
   "email": "gamemy177@gmail.com",
   "resetToken":"fcf4769d-adb7-49c5-82e8-303a66ecbfa9",
   "newPassword":"12345678@dK" 
}


### checking user details
GET http://localhost:3700/users/checkUserDetails/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3NzY3Nzc3NS0xODNhLTQ4YzktODAxMC1jNzc3MGEzZTk4NGUiLCJmdWxsTmFtZSI6IkVyaWNrIEt5YWxvIiwidXNlcm5hbWUiOiJfQGVyaWNrMTIzIiwiZW1haWwiOiJlcmlja2t5YWxvQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjp0cnVlLCJpc1NlbmQiOmZhbHNlLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL21lZGlhLmlzdG9ja3Bob3RvLmNvbS9pZC8xMzAwODQ1NjIwL3ZlY3Rvci91c2VyLWljb24tZmxhdC1pc29sYXRlZC1vbi13aGl0ZS1iYWNrZ3JvdW5kLXVzZXItc3ltYm9sLXZlY3Rvci1pbGx1c3RyYXRpb24uanBnP3M9NjEyeDYxMiZ3PTAmaz0yMCZjPXlCZXliYTBoVWtoMTRfamd2MU9LcUlIMENDU1dVXzRja1JrQW95MnA3M289IiwiaWF0IjoxNzAyNjMxMjI3LCJleHAiOjE3MDI4MDQwMjd9.vPEqXjXa9thiIXSdPFq6WTRaAtv5-hkSxqhxwuUDMMY



#### deleting user
DELETE http://localhost:3700/users/delete/13994250-847e-4545-9232-af9cd787b196/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3NzY3Nzc3NS0xODNhLTQ4YzktODAxMC1jNzc3MGEzZTk4NGUiLCJmdWxsTmFtZSI6IkVyaWNrIEt5YWxvIiwidXNlcm5hbWUiOiJfQGVyaWNrMTIzIiwiZW1haWwiOiJlcmlja2t5YWxvQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIndlbGNvbWVkIjp0cnVlLCJpc1NlbmQiOmZhbHNlLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL21lZGlhLmlzdG9ja3Bob3RvLmNvbS9pZC8xMzAwODQ1NjIwL3ZlY3Rvci91c2VyLWljb24tZmxhdC1pc29sYXRlZC1vbi13aGl0ZS1iYWNrZ3JvdW5kLXVzZXItc3ltYm9sLXZlY3Rvci1pbGx1c3RyYXRpb24uanBnP3M9NjEyeDYxMiZ3PTAmaz0yMCZjPXlCZXliYTBoVWtoMTRfamd2MU9LcUlIMENDU1dVXzRja1JrQW95MnA3M289IiwiaWF0IjoxNzAyNjMxMjI3LCJleHAiOjE3MDI4MDQwMjd9.vPEqXjXa9thiIXSdPFq6WTRaAtv5-hkSxqhxwuUDMMY



###follow and unfollow user
POST http://localhost:3700/users/followUnfollowUser/
Content-Type: application/json

{
   "followingUserID":"13994250-847e-4545-9232-af9cd787b196", 
   "followedUserID":"118a3986-224c-4fbd-97dd-a571d1ae9c6a"
}

### get followers
GET http://localhost:3700/users/getFollowers/99e18f3a-f7d9-4bb7-80e2-b9f17bd2081b


### get following
GET http://localhost:3700/users/getFollowings/31230ca0-094a-486c-9041-7a9b2aacf398



############################# ENDPOINTS FOR POSTS ##########################


###### creating new post
POST http://localhost:3700/posts/create
Content-Type: application/json

{
    "userID": "cac49075-bc3f-4bce-a581-b83d2420ad1b",
    "caption": "This brings the best moments in the region in Kenya",
    "postImage": ["https://media.istockphoto.com/id/937510970/photo/smart-tv-mockup-with-black-glossy-screen-on-console-in-living-room.jpg?s=2048x2048&w=is&k=20&c=0_fvqr0Hrqd3NR9C5tsDF2ys6rQQBJEcYI_o6fyvlg0="]
}


### fetching all posts

GET http://localhost:3700/posts/all


### fetching one post
GET http://localhost:3700/posts/single/740057a8-6906-471c-8d1f-58f7e2783c23


###### Updating post
PUT  http://localhost:3700/posts/update/740057a8-6906-471c-8d1f-58f7e2783c23
Content-Type: application/json

{
    "userID": "933706eb-e1eb-40f6-9cb4-1c14e7e6e1fe",
    "caption": "They are remaining two regions with Nyeri",
    "postImage": ["https://media.istockphoto.com/id/1430080532/photo/bedroom-without-sheets.webp?b=1&s=612x612&w=0&k=20&c=7_c725vsPgGRxQJLD13VAt5zOk6TvFT4KWZba4RYBfg="]
  }


# Deleting a post
###
DELETE http://localhost:3700/posts/delete/740057a8-6906-471c-8d1f-58f7e2783c23/



###### liking a post
POST http://localhost:3700/posts/likepost/
Content-Type: application/json

{
    "userID": "933706eb-e1eb-40f6-9cb4-1c14e7e6e1fe",
    "postID": "33d87867-9ad2-4c52-9b4e-a67657386156"
}


###### unlike a post
POST http://localhost:3700/posts/unlikepost/
Content-Type: application/json

{
    "userID": "933706eb-e1eb-40f6-9cb4-1c14e7e6e1fe",
    "postID": "33d87867-9ad2-4c52-9b4e-a67657386156"
}

###### alllikes for a post
GET http://localhost:3700/posts/alllikes/33d87867-9ad2-4c52-9b4e-a67657386156/



###### likes count
GET http://localhost:3700/posts/postlikecount/33d87867-9ad2-4c52-9b4e-a67657386156




###################### ENDPOINTS FOR COMMENTS #################################

###### creating new comments
POST http://localhost:3700/posts/addComment/
Content-Type: application/json

{
    "userID": "99e18f3a-f7d9-4bb7-80e2-b9f17bd2081b",
    "postID": "2c3c9ae4-22d4-4c36-ad8e-e027438b3222",
    "content": "lovely"
}


### fetching all comments

GET http://localhost:3700/posts/allComments/


#### fetching comments from single post
GET http://localhost:3700/posts/getpostcomments/caa4ff74-fdaf-4a1f-a646-80c60754f32c


###update comment
PUT http://localhost:3700/posts/updatecomment/a8c2184c-6a77-40c7-b898-47f818732144
Content-Type: application/json

{
  "userID": "99e18f3a-f7d9-4bb7-80e2-b9f17bd2081b",
  "content": "new working style"
}


###delete comment
DELETE http://localhost:3700/posts/deletecomment/1f92aec2-b3e6-463e-87dd-de13dd3a590a



###### creating new reply for the comment
POST http://localhost:3700/posts/createreply/
Content-Type: application/json

{
    "userID": "63b8a570-bee0-484f-bf71-a23fddc39549",
    "commentID": "e7e388d9-80ec-436e-a8ce-ba1c68603c8c",
    "text": "wonderfull"
}

### fetching all replies for specific comment

GET http://localhost:3700/posts/allreplies/e7e388d9-80ec-436e-a8ce-ba1c68603c8c


###update comment reply
PUT http://localhost:3700/posts/updatereply/
Content-Type: application/json

{
  "replyID": "e7e388d9-80ec-436e-a8ce-ba1c68603c8cb",
  "text": "nice moment"
}


###### like a coment
POST http://localhost:3700/posts/comment/like/
Content-Type: application/json

{
    "userID": "63b8a570-bee0-484f-bf71-a23fddc39549",
    "commentID": "e7e388d9-80ec-436e-a8ce-ba1c68603c8c"
}

###### unlike a coment 
POST http://localhost:3700/posts/comment/unlike
Content-Type: application/json

{
    "userID": "933706eb-e1eb-40f6-9cb4-1c14e7e6e1fe",
    "commentID": "00d7e7c2-0551-452c-bfab-77dad59cc8e8"
}


###delete comment reply
DELETE http://localhost:3700/posts/deletereply/39050b2d-731b-480a-afc0-f7d20dfb3743


